
server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: hotel_rating_db
  application:
    name: RATING-SERVICE

  config:
    import: optional:configserver:http://localhost:8085


okta:
  oauth2:
    issuer: https://dev-38965811.okta.com/oauth2/default
    audience: api://default


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka